import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavWrapper from "../components/NavWrapper";
import { Toaster } from "@/components/ui/sonner";
import { createClient } from "@/utils/superbase/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  console.log("user data", user);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar (fixed / sticky) */}
        <NavWrapper />

        {/* Page content pushed BELOW navbar */}
        <main className="pt-16 min-h-screen">
          {children}
        </main>

        <Toaster />
      </body>
    </html>
  );
}
